variables:
  CI: "false"
  AWS_ACCESS_KEY_ID: "AKIASDYGBXDRUIWMD35W"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_DEFAULT_REGION: "us-east-2"
  S3_BUCKET_NAME: "fvb-grupo9-front"

#--------Stage--------
stages:
  - build
  - package
  - deploy

#--------Build---------
build_frontend:
  stage: build
  image: node:latest
  script:
    - cd Frontend
    - cd digitalBooking-front
    - npm install
    - npm run build


#--------Deploy--------
deploy_frontend:
  stage: deploy
  image: python:3.6
  script:
    - pip install awscli==1.18.211
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws s3 cp Frontend/digitalBooking-front/build s3://$S3_BUCKET_NAME/ --recursive